### ISSUE TITLE
Separate private and public methods

### ISSUE THREAD

**Issue by paulobruno** [natema/WorldDynamics.jl#102]
In Julia, all fields are accessible. The common way to differentiate between "public" and "private" ones is to export some while keeping others internally. However, since we have several internal modules used to separate the code, we cannot really export the "public" fields. 
There are other different ways of separating public and private methods. The simplest one to suit our needs seems to be putting an underscore at the beginning of every private field. We already do this on [some methods](https://github.com/natema/WorldDynamics.jl/blob/635e2926800e7d1df4ed1eb3226054de32b43c50/src/World3/agriculture/plots.jl#L71), but not all of them. I don't like this solution, because the user can easily access internal methods, for example by using tab completion.

Independently on how it should be in the future, the most important fact is that it shouldn't be mixed, as it is now.

**Comment by natema** [comment]
>  However, since we have several internal modules used to separate the code, we cannot really export the "public" fields. 

I'm not sure I see the issue with using the standard export statement.

**Comment by paulobruno** [comment]
If we follow the standard export case, we should export all fields the user is expected to access. For example, we should export all `param`. But if we export them, we get conflicts, because all systems have `params`.

**Comment by paulobruno** [comment]
Since we didn't define a public API yet, it doesn't seem worth spending too much time on this. For now, I'll just add a leading underscore in private fields. After we have a well-defined public API, then we can think about different possibilities.

**Comment by paulobruno** [comment]
Fixed by #123
