### ISSUE TITLE
Add column with complete variable names to documentation

### ISSUE THREAD

**Issue by natema** [natema/WorldDynamics.jl#117]
The [Variable and (ODE) subsystem correspondance](https://natema.github.io/WorldDynamics.jl/stable/world3/#Variable-and-(ODE)-subsystem-correspondance) section has a nice table listing all the variables in World3, but currently shows only the acronyms and not the complete name, that could be useful for understanding the system.

**Comment by paulobruno** [comment]
Fixed by #125
