### ISSUE TITLE
 Add example of changing equations

### ISSUE THREAD

**Issue by paulobruno** [natema/WorldDynamics.jl#18]
It is possible to do this without changing the package code, but it's not trivial. Currently, we have to look for the equation we want to change in the vector of system equations manually.

**Comment by natema** [comment]
I think this is fair enough atm. Also, after a first example where we change an equation of the whole system, we can have another example where we change an equation of a subsystem. From that point of view, equations are already grouped in subsystems, so looking for them shouldn't be terrible.

**Comment by paulobruno** [comment]
I added an example in the Agriculture fig. 4.87.

**Comment by universmile** [comment]
At the moment, one has to print the array of equations and look at its index, which seems cumbersome. We should find some remedy before implementing the remaining 11 figures that require editing equations, then have it documented.

**Comment by natema** [comment]
I don't see a natural way to address this point. 
Can be an enhancement for a future version, but atm unless you have a proposal, I'll let it as is.

**Comment by paulobruno** [comment]
Since we have a way to do so, which was the goal of the issue, i'm closing it.
I'll open a new one to improve the current process of changing equations.
