### ISSUE TITLE
Missing picture in tutorial

### ISSUE THREAD

**Issue by natema** [natema/WorldDynamics.jl#36]
[Here](https://natema.github.io/WorldDynamics.jl/dev/tutorial/#Replicating-historical-runs), the documentation mentions a picture which is not shown. 
In fact, there is no link to any picture in [the source of the tutorial page](https://github.com/natema/WorldDynamics.jl/blob/6ca2d5b1b61c9deb8d557b6ce29b1a223547fa7d/docs/src/tutorial.md).

**Comment by natema** [comment]
Actually this should be fixed by #37 .

**Comment by piluc** [comment]
Done.
