### ISSUE TITLE
Plot all figures from the book

### ISSUE THREAD

**Issue by paulobruno** [natema/WorldDynamics.jl#4]
Although the standard figures are currently implemented and at least very close to the original ones, implementing all of them (including the parameter variations) would increase the confidence that the current code is indeed in pair with the original.

**Comment by natema** [comment]
I opened #76 regarding how we are currently reproducing the figures.

**Comment by paulobruno** [comment]
I was a naive young guy when I created this issue :sweat_smile: 
Even after more than five months, we don't have all of the figures implemented.
Since we handled most of them and only very few are missing, I'll close this issue and we'll deal specific cases on their own issues.
