### ISSUE TITLE
Direct integration of the scenarios in the package

### ISSUE THREAD

**Issue by natema** [natema/WorldDynamics.jl#63]
Currently, the tutorial shows how to reproduce a scenario by using the source files of the package. 
We should allow users to reproduce a scenario without having to access the source files.

**Comment by paulobruno** [comment]
The snippet below is an example on how to reproduce a figure currently implemented.
```
using WorldDynamics
fig = WorldDynamics.World3.fig_7()
```

**Comment by natema** [comment]
Closed by #66 .
