### ISSUE TITLE
Mismatch Fig. 3.46

### ISSUE THREAD

**Issue by universmile** [natema/WorldDynamics.jl#78]
In Fig. 3.46, there is a slight difference for the `sopc` variable. Its corresponding plot should exhibit a higher peak around 1980.

The issue persists when changing the solver.

<img width="1199" alt="Fig  3 46" src="https://user-images.githubusercontent.com/32130503/192578333-d4b730ac-8eab-45d2-b6b1-16e69d628100.png">

**Comment by natema** [comment]
Closed by #108 .
