### ISSUE TITLE
Little bump fluctuation at the initialization

### ISSUE THREAD

**Issue by universmile** [natema/WorldDynamics.jl#79]
For some figures of Chapter 2 and Chapter 7, there is an incorrect bump during the initialization. This bump concerns most of the time the variable `cbr`.

While some major fluctuations of the `cbr` variable have been fixed by changing the solver (cf. #60), such initial bump resist and seems unrelated to the choice of the solver.

Examples :
<img width="1316" alt="Fig  7 10" src="https://user-images.githubusercontent.com/32130503/192595997-1d62ff82-d421-4597-b473-40aeee9ece13.png">
<img width="1230" alt="Fig  7 11" src="https://user-images.githubusercontent.com/32130503/192596603-3448f961-665e-46fb-8ab1-303994068ad0.png">

Example affecting other variables in addition to the `cbr` variable :
<img width="1413" alt="Fig  7 2" src="https://user-images.githubusercontent.com/32130503/192596294-390670d6-45a6-460d-9547-7b7ab70e486c.png">

**Comment by natema** [comment]
This initial bump can be a simple consequence of the fact that we solve the system in _continuous time_: you can check that the behavior is the same after approx. 5 years after the start.
The bump should then disappear when we solve the system in the same way, namely with `Euler()` and stepsize `dt=5.0`. 
I will test it now. 

A related point is that the current `solve` interface doesn't allow to pass the stepsize `dt` keyword argument when choosing `Euler()` as integration method. 
We might open an issue regarding enabling the possibility to pass to our `solve` any argument that is supported by ModelingToolkit.

**Comment by natema** [comment]
I'm puzzled... using the (supposedly) same method than that in World3 messes up many trajectories: 
![image](https://user-images.githubusercontent.com/2920162/192794746-988b820e-f2ee-4423-b3d0-3f5ad5c57431.png)

Here's the source: 
```jl
using WorldDynamics, .World3
using ModelingToolkit, DifferentialEquations 
##
@variables t

nr_parameters_7_10 = World3.NonRenewable.getparameters()
nr_parameters_7_10[:nri] = 2e12
##
system = World3.historicalrun(nonrenewable_params=nr_parameters_7_10)
##
sys = structural_simplify(system)
timespan = (1900, 2100)
prob = ODEProblem(sys, [], timespan)
solution = ModelingToolkit.solve(prob, Euler(), dt=5.0)
##
plotvariables(solution, (t, 1900, 2100), World3.variables_7(); title="Fig. 7.10")
```

Maybe I'm forgetting about some choices that we made when we derived the differential equations associated to their discrete system, and considering the Euler method now is not equivalent. 
This should be further investigated...

**Comment by paulobruno** [comment]
With the changes in #94, @piluc decided to remove the artificial initialization of `frsn` that used a clip function. `frsn` directly affects the values of several other variables, including "crude birth rate" (cbr). 
As a result, there is no bump anymore, but the initialization starts lower from the beginning, as you can see in the figure below.

![updated fig 7.10](https://user-images.githubusercontent.com/6677872/193115920-275cd59d-17b9-40cf-a81e-52b6a1c6dfd9.png)

As @natema pointed out, this is not necessarily an error in our side, but a discrepancy between the discretization used in the book and our solution with ModelingToolkit. 
If everyone is on the same page, I think we can close this issue.
